name: Actions Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run prod
      - run: cd dist && firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GIT_ADMIN_TOKEN: ${{ secrets.GIT_ADMIN_TOKEN }}
